spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
zuul:
  host:
    connect-timeout-millis: 1000000
    socket-timeout-millis: 6000000
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 1000000     