spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 20KB

# Disable Hystrix timeout globally (for all services)
#hystrix.command.default.execution.timeout.enabled: false


# Disable Hystrix timeout for a single service
#hystrix.command.recommender-registry-services.execution.timeout.enabled: false

# Increase the Hystrix timeout to 60s (globally)
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

#logging:
#  level:
#    root: DEBUG